<?php
/*
 * Reads in files generated by the Python script "convert.py"
 * and adds the data in those files to the database.
 *
 * The files corresponding to the tables listed in $tableNames will
 * be parsed. The data in those files will then be added to the
 * appropriate tables.
 *
 * 	NOTE: The imported files must be named after the
 * 	tables in the database. For example, to load data
 * 	into the Mentor table, the file would need to be
 * 	named Mentor.csv.
 *
 * This script executes the python script given on the command line using
 * old database given as stdin for the script.
 */

/* Run the python script to generate parsable files for the new database */
if(count($argv) != 7)
{
    print("Usage: php $argv[0] hostName userName password databaseName path/to/convert.py path/to/oldDatabase.csv\n");
    exit();
}
$hostName = $argv[1];
$userName = $argv[2];
$password = $argv[3];
$databaseName = $argv[4];
$convert = $argv[5];
$oldDatabase = $argv[6];

$database = mysqli_connect($hostName,$userName,$password,$databaseName);

exec("$convert < $oldDatabase");

// Check connection
if (mysqli_connect_errno($database))
{
    echo "Failed to connect to MySQL: " . mysqli_connect_error();
    exit();
}

/* 
 * The names of the tables which need to be written in an Excel
 * readable format.
 */
$tableNames = array("Mentor", "Mentee");


for($i = 0; $i < count($tableNames); $i++)
{
    $tableName = $tableNames[$i];

    /*
     * The current file being parsed.
     */
    $fileName = $tableName . ".csv";

    $toParse = fopen($fileName, "r");

    while(!feof($toParse))
    {
	$row = fgets($toParse);

	/* Build insertion query */
	$row = trim($row);
	if($row != NULL && $row != "")
	{
	    $valuesArray = explode(",",$row);
	    $valuesString = "";

	    for($j = 0; $j < count($valuesArray); $j++)
	    {
		if($j === 0)
		{
		    $valuesString = $valuesString . "'" . $valuesArray[$j] . "'";
		}
		else
		{
		    $valuesString = $valuesString . ",'" . $valuesArray[$j] . "'";
		}
	    }

	    $query = "INSERT INTO $tableName VALUES($valuesString)";

	    /* Add the row to the database */
	    mysqli_query($database,$query);
	}
    }

    fclose($toParse);
}

mysqli_close($database);
?>
