<?php
/*
 * IMPORTANT:
 * 	This script requires that the tables for which the data
 * 	is going to be added to already exists in the database.
 * 	Obviously there will not be any data in the tables, but
 * 	the tables with the proper column names and column order
 * 	must exist.
 *
 * 	The easiest way to accomplish this is to load one of the
 * 	saved .sql files of the database. You should probably
 * 	load the most recent one. The older .sql files may not
 * 	be compatible with the convert.py scripts output and
 * 	therefore are not compatible with this script.
 *
 *
 * Reads in files generated by the Python script "convert.py"
 * and adds the data in those files to the database.
 *
 * The files corresponding to the tables listed in $tableNames will
 * be parsed. The data in those files will then be added to the
 * appropriate tables.
 *
 * 	NOTE: The imported files must be named after the
 * 	tables in the database. For example, to load data
 * 	into the Mentor table, the file would need to be
 * 	named Mentor.csv.
 *
 * This script executes the python script given on the command line using
 * old database given as stdin for the script.
 */
require 'importDatabaseFunctions.php';

/* Parse command line arguments */
if(count($argv) != 7)
{
    print("Usage: php $argv[0] hostName userName password databaseName path/to/convert.py path/to/oldDatabase.csv\n");
    exit();
}
$hostName = $argv[1];
$userName = $argv[2];
$password = $argv[3];
$databaseName = $argv[4];
$convert = $argv[5];
$oldDatabase = $argv[6];

$database = mysqli_connect($hostName,$userName,$password,$databaseName);

// Check connection
if (mysqli_connect_errno($database))
{
    echo "Failed to connect to MySQL: " . mysqli_connect_error();
    exit();
}

importDatabase($database,$convert,$oldDatabase);
?>
